# Introduction {#intro}

This is a user manual for the High-Performance-Server (HPC) of the GIScience chair at the Friedrich-Schiller-University Jena.

Its main purpose is to do R processing and its setup is tailored towards this.
Nevertheless, of course also any job can be submitted to the HPC.
However, the following manual will focus on getting R code running.

The big advantage of a HPC is that users can submit jobs to ONE remote server which then distributes the work across multiple machines in the background.
Incoming processing requests (jobs) are handled by the installed scheduler (SLURM), taking away the work of scheduling the job and the fear of clashing with other users.
The status of the job request can be queried easily.
Administration is simpliefied by provisioning all compute nodes with the same virtual image.
This way, update tasks are reduced and differences between the machines are avoided.
Administration is further simplified by using the [Spack]() package manager as this application allows for version-agnostis library installations on the user level without the need of requesting and waiting for custom installation to the admin.

The $HOME directory of every used is shared across all nodes, avoiding the need to keep data and scripts in sync across multiple machines.

## Web Address

* gisc.ads.uni-jena.de (short for GIS cluster)
* IP: 10.35.158.19

## Hardware

Each node of the HPC has the following hardware:

- CPU: Threadripper 2950X, 16-core, 3.5 GHz - 4.4 GHz
- RAM: 126 GB DDR4 
- 1 TB M2 SSD

Currently, three nodes are available for processing. 
The master node (which will be referred to as the _system management server_ (SMS) from here on) is currently not used as it is hosting the _Rstudio Server_ application.
Depending on the load, we might also add it as a computing node in the future.

## Software

The HPC was built following the installation guide provided by the [Open HPC](https://openhpc.community/) community (using the "Warewulf + Slurm" edition).
It is currently running on a CentOS 7.6 operating system using the CentOS main-line Kernel (currently at version 4.20).
The scheduler that is used for queuing processing job requests is [SLURM](https://slurm.schedmd.com/).
Load monitoring is performed via [Ganglia](http://ganglia.sourceforge.net/). 
A live view is accessable [here](http://10.35.158.19/ganglia/?r=hour&cs=&ce=&m=load_one&s=by+name&c=&tab=m&vn=&hide-hf=false).
[Spack][https://spack.io/] is used as the package manager.
More detailed instructions on the scheduler and the package manager can be found in their respective chapters.

