# Libraries and Environment Modules {#libraries}

## Introduction

Most system relevant libraries are installed via [Spack](spack.io).
However, as a user you do not need to worry about this since you are loading everything via "environment modules".
Available modules can be queried using `modules avail`.

For setup reasons, please put the following at the top of your `~/.bashrc` file

```sh
export SPACK_ROOT=/opt/spack
. $SPACK_ROOT/share/spack/setup-env.sh
```

Please use only module list with the suffix "linux-centos7-zen".
Here is a snapshot:

```sh
------------------------- /opt/spack/share/spack/modules/linux-centos7-zen -------------------------
   byobu-5.127-gcc-9.2.0-x5e5mnz    (L)    pkg-config-0.29.2-gcc-9.2.0-tsjdiyy
   ccache-3.3.4-gcc-9.2.0-7klqklq   (L)    proj-4.9.2-gcc-9.2.0-3skzcql
   cmake-3.15.3-gcc-9.2.0-e7uy3lq          proj-5.2.0-gcc-9.2.0-az6mkj5        (L)
   curl-7.63.0-gcc-9.2.0-zqkxl74    (L)    proj-6.1.0-gcc-9.2.0-i25e6py
   gdal-2.4.2-gcc-9.2.0-vbgkeil            r-rgdal-1.4-4-gcc-9.2.0-elwh3bl
   gdal-3.0.1-gcc-9.2.0-2rbxot4     (L)    r-rgdal-1.4-4-gcc-9.2.0-u3ixmgg
   geos-3.7.2-gcc-9.2.0-hn6gflr     (L)    sqlite-3.29.0-gcc-9.2.0-abag2du
   neovim-0.3.4-gcc-9.2.0-tsvynsq   (L)    zlib-1.2.11-gcc-9.2.0-yuybfrv       (L)
   openblas-0.3.7-gcc-9.2.0-gwikytn (L)

------------------------------------ /opt/ohpc/pub/modulefiles -------------------------------------
   EasyBuild/3.9.2       clustershell/1.8.1    hwloc/2.0.3    pmix/2.2.2           valgrind/3.15.0
   autotools             cmake/3.14.3          ohpc           prun/1.3
   charliecloud/0.9.7    gnu8/8.3.0            papi/5.7.0     singularity/3.2.1
```

## Loading modules

Modules can be loaded via `module load <module>`.

First, you need to load a C compiler as most programs depend on it.
This module is the only one that you should which uses `gcc-4.8.5`.
Make sure to also put this one into your `~/.bashrc` file!

```sh
module load gcc-9.2.0-gcc-4.8.5-o3uv2jk
```

Now you can (for example) load GDAL:

```sh
module load gdal-3.0.1-gcc-9.2.0-2rbxot4 
```

You can check that it worked via 

```sh
gdalinfo --version
```

## Checking loaded modules

```sh
module list
```

## Default modules

It is useful to have some modules loaded by default when logging in to the server.
Simply add them to `~/.bashrc`.

When running R for spatial analysis, the following are required:

```sh
module load gdal-3.0.1-gcc-9.2.0-2rbxot4
module load geos-3.7.2-gcc-9.2.0-hn6gflr
module load proj-5.2.0-gcc-9.2.0-az6mkj5
module load udunits2-2.2.24-gcc-9.2.0-lbs7534
module load pandoc-2.7.3-gcc-9.2.0-tlzhs7d
module load openblas-0.3.7-gcc-9.2.0-gwikytn
module load zlib-1.2.11-gcc-9.2.0-yuybfrv
module load libiconv-1.15-gcc-9.2.0-gbu6lja
```

Furthermore, I recommend the following ones (don't forget to append your version and compiler):

```sh
module load byobu-5.127-gcc-9.2.0-x5e5mnz
module load git-2.21.0-gcc-9.2.0-hhkbkhg
module load ccache-3.3.4-gcc-9.2.0-7klqklq
```

You might wonder why you shouldn't add a R version to this list?
The answer is that it will conflict with RStudio-Server.
Whenever opening a session, your `~/.bashrc` file is sourced.
If you specify an R version there, it will always override what is specified in the RStudio-Server settings related to R-versions.
So yes, you always need to specifically load R when logging into a new session.

Also make sure that `GDAL` and friends are loaded in your `.bashrc` file as otherwise RStudio Server will not find them.

If you need to load specifc modules for a project, try to [create a wrapper for your project](#wrapper).

## R

All versions from v3.4.4 upwards are installed.
R is not managed via env modules currently as it causes some problems with RStudio Server.
R versions are installed at `/opt/R/<version>`.

To load a specific R version, call the following from the terminal

```sh
export R_HOME=/opt/R/<version>/lib64/R
```

and then execute `R` (or preferably [radian](#radian)).

You might find the following aliases helpful which you can put into `~/.bashrc`:

```sh
alias r344="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.4.4-rzhfe5glzycgamye6qlrvsnetronftpw/rlib/R && radian"
alias r350="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.0-qpdg7ahjfznh5ivoj4eetzbr3bf4cad7/rlib/R && radian"
alias r351="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.1-rjchaiabtobk76x2th2ukxsstyk2lnoo/rlib/R && radian"
alias r352="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.2-ikmvwxzm4redzk5rhubfjjwzkoaskfbl/rlib/R && radian"
alias r353="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.5.3-g6smxppqwljnukmag23jfixrd5vabxcd/rlib/R && radian"
alias r360="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.6.0-fn2ixao7s2mrvweuhhkceptmew6pgqra/rlib/R && radian"
alias r361="export R_HOME=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/r-3.6.1-cfrumokg7m7jx4acgu7pwg5suhcngj35/rlib/R && radian"
```

This enables you to launch the specific R version using the set command, e.g. `r360` will launch R v3.6.0.

## RStudio Server

RStudio Server Pro is running on port 8787 (https://edi.geogr.uni-jena.de:8787).

## Shiny Server

Shiny server is running on port 3838 with user support.
This means users can place apps in `$HOME/Shinyapps/` and they will be deployed as `http://edi.geogr.uni-jena.de:3838/<username>/<appname>`.

Note the `http` (`https` is only available in the Pro version).

Exemplary apps:

- http://edi.geogr.uni-jena.de:3838/patrick/hyperspectral/
- http://edi.geogr.uni-jena.de:3838/jannes/cluster_map/

## Libraries

If you cannot find a module you want to use, check it Spack supports it via `spack list <module>` and contact an admin to install it for you.

### Docker

Docker is installed on the frontend only (for example to convert .html to .pdf).
To use `docker`, your user needs to be added to the "docker" group.
Please contact an Admin in case you want to use it.

### OSRM

[Open Source Routing Machine](https://github.com/Project-OSRM/osrm-backend) is installed.

Start the server with `osrm-routed`.  
More information can be found [here](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM).

### GDAL {#gdal}

Check `module avail` and look for GDAL to see which versions are available.

## Getting Started

If you worked through all these steps, you are almost good to go.
Here are have some further recommendations to make your life easier.

#### byobu

`byobu` is a wrapper for your SSH session that makes it possible to close your terminal session and not loose the command running in it.
If you start long running jobs, you can safely start them in a `byobu` window without worrying about them to quit once you shut down your machine.

Run `byobu` after being logged in and a `byobu` session will be launched.

You can open multiple ones with `byobu -S <session name>`, e.g. `byobu -S session2`.
Once you have multiple ones open, an interactive prompt will ask you which one you want to start next time.

#### radian {#radian}

`radian` is an optimized R command line tool. 
You will notice the benefits compared to the default `R` once you start using it.
You need to install it via `pip` which is already installed if you installed `python`.

Usually `setuptools` needs to be upgraded first.

```sh
pip install --user --upgrade setuptools
pip install --user radian
```

Now you can either always use `radian` or set an alias in your `.bashrc` , e.g. `alias r="radian"`.
Note that `radian` only works if you have set the env variable `R_HOME` correctly.
See [here](#R) for more details.

If is does not work at this moment, you might need to add the binary to your `$PATH` variable in your `~/.bashrc`.

```sh
export PATH=~/.local/bin:$PATH
```

#### ccache

If you load `ccache`, you will speed-up source installations of R packages a lot.
(On Linux, all R packages are installed from source.)
Besides loading `ccache`, you also need to create the following file in your home directory (`~/.R/Makevars`):

(Note that you need to create the folder first, it does not exist by default (`mkdir ~/.R/`).)

```sh
CXX_STD = CXX14

VER=
CCACHE=ccache
CC=$(CCACHE) gcc $(VER)
CXX=$(CCACHE) g++$(VER)
C11=$(CCACHE) g++$(VER)
C14=$(CCACHE) g++$(VER)
FC=$(CCACHE) gfortran$(VER)
F77=$(CCACHE) gfortran$(VER)
```

When installing a package now, you will occasionally see that the `gcc` lines are prefixed with `ccache`.
This means that this `gcc` call was already executed once and is now loaded from the cache rather than being run again.
This saves a lot of time, especially for packages that take long to install (`dplyr`, `Rcpp`, `stringi`).

#### Create a wrapper for your project {#wrapper}

Usually you might want to use a _packrat_ library in a specific directory with a specific R version.
Rather than navigating there all the time by hand and loading the R version manually, you can create an alias that does this for you.
You can of course also use this approach without _packrat_ - just to load a specific version. 

```
alias my-project="cd /path/to/project && <load custom env module> && r361"
```

Put this in your `.bashrc` and save time :)
