# Troubleshooting and Cautionary Notes

## Cautionary Notes

## FAQ

**Question**: I ran `sinfo` and saw that the state of the nodes is "down".  
**Answer**: Please contact the admin (patrick.schratz@uni-jena.de) to resume the nodes.

**Question**: I ran `sinfo` and see that some nodes have status "mix" and some "alloc". What are the differences?  
**Answer**: "mix" means that the node is not fully loaded and is in a mixed state between processing and being idle. "alloc" means that the node is fully allocated.

**Question**: I ran `spack load <library>` and got `==> Error: the constraint '['gdal@2.3.3']' matches multiple packages:`. What shall I do?  
**Answer**: This means that multiple instances of this library are installed. Sometimes this is unavoidable, for example some libraries request GDAL being built against Python2, others against Python3. In this case, do the following:

1. Run `spack find --long <library>`
2. Use the has identifier to load the package, e.g. `spack load /jsajw88`.
3. If you use this library regulary, put this command into your `.bashrc` file.
4. If you experience problems during usage, try the other one.
5. If you wanna see the differences between both, do `spack find --variants <library>`

**Question**: I ran `spack load <library` and got the error message "Even though <library> is installed, no tcl module has been generated for it".  
**Answer**: This means that the module 

**Question**: When trying to connect to RStudio Server, I get "Unable to connect to service" when opening a session.  
**Answer**: There can be multiple reasons for that. Here is a checklist:

- Do you have `spack load gcc@7.3.0` in your `~/.bash.rc` file?
- Are you using `https://` to connect? `http://` won't work.
- Connect to `edi.geogr.uni-jena.de:8787/home` and kill the problematic session. Then try again.

**Question**: When loading GDAL on the nodes I get linking problems or see an "undefined reference" error.
**Answer**: Most likely a leftover of a GDAL source installation is causing trouble. See the instruction in the [GDAL](#gdal) section on what to put in your clustermq template.

**Question**: I cannot install `udunits2`. What shall I do?  
**Answer**: Install it via `install.packages('udunits2', type = 'source', repo = 'cran.rstudio.com', configure.args='--with-udunits2-include=/usr/include/udunits2'`.

**Question**: I cannot install `rgdal`. What shall I do?  
**Answer**: Set the dynamic linker explicit to the respective libraries. For example for PROJ: 

```r
install.packages("rgdal", configure.args = c("--with-proj-include=/opt/spack/opt/spack/linux-centos7-
    x86_64/gcc-7.3.0/proj-5.0.1-kbodwcnjxemfewjbke6lbzp44z52umpa/include", "--with-proj-lib=/opt/spack/op
    t/spack/linux-centos7-x86_64/gcc-7.3.0/proj-5.0.1-kbodwcnjxemfewjbke6lbzp44z52umpa/lib"))
```

You can optionally set this in you `.Rprofile` to not have to type it on every install:

```r
options(configure.args=list(rgdal=c("--with-proj-include=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/proj-5.0.1-kbodwcnjxemfewjbke6lbzp44z52umpa/include",
"--with-proj-lib=/opt/spack/opt/spack/linux-centos7-x86_64/gcc-7.3.0/proj-5.0.1-kbodwcnjxemfewjbke6lbzp44z52umpa/lib")))
```

**Question**: I am getting installation errors on R >3.6.0 containing either `Error in slibs[are_shared] : invalid subscript type 'list` or `version 'ZLIB_1.2.9' not found`.  
**Answer**: Try turning off staged installs via `Sys.setenv("R_INSTALL_STAGED"=FALSE)` or by setting the env var globally in your .bashrc file. See https://github.com/r-lib/later/issues/93 for more information.
